dependencies:
- nodejs==15.*
- pip==20.2.*
- python==3.9.*

- syncthing==1.18.6

# data8
- matplotlib==3.4.3
- ipympl==0.7.0
- pandas==1.3.2
- scipy==1.7.1
- statsmodels==0.12.2
- seaborn==0.11.2
- scikit-learn==1.1.1
- sympy==1.10.1
- astropy==5.0.4
- ephem=>4.1.2
- xlrd==2.0.1
- ffmpeg==5.0.1
- biopython==1.79
# Otter is pulled in via infra-requirements.txt, since it's present in all hubs

# Items not in conda forge
- pip:
# Export notebooks as PDFs with Chrome
  - notebook-as-pdf==0.5.0
# Conda only has 0.12.0
  - folium==0.12.1
  - okpy==1.18.1
  - datascience==0.17.0
  - jupyter_contrib_nbextensions==0.5.1
  - pydna==4.0.7
  - orfipy==0.0.4
  - einsteinpy==0.4.0
