name: Data Archival Request
description: Retrieve my old Datahub files
labels: support
assignees:
- felder
body:
  - type: markdown
    attributes:
      value: |
        Please follow the sections in the template and provide us the required information to retrieve your files! There are more than 10+ hubs serving diverse instructional needs of the campus community. We require you to identify the correct URL to your files in the exact hub used as part of your course.  
  - type: textarea
    attributes:
      label: Email Id 
      description: Share the Berkeley Email Id which you used to access Datahub!
    validations:
      required: true
  - type: input
    attributes:
      label: Graduation Details
      description: Did you already graduate?
    validations:
      required: true
  - type: input
    attributes:
      label: Term/Year
      description: Identify the term of the semester (Fall/Spring/Summer) and the year of your course enrollment
    validations:
      required: true     
  - type: input
    attributes:
      label: Login Detail
      description: When was the last time you logged in to the hub?
    validations:
      required: true 
  - type: textarea
    attributes:
      label: Link to Datahub Folder
      description: Link to the location where your archived files are kept!
      value: |
        - Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz
    validations:
      required: true
